# Generated by Django 4.2.10 on 2024-04-14 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizbank.course'),
        ),
    ]
