# Generated by Django 4.2.10 on 2024-04-16 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ef', models.FloatField(default=2.5, verbose_name='易度系数(EF)')),
                ('interval', models.IntegerField(default=1, verbose_name='复习间隔（天数）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('next_review_date', models.DateTimeField(verbose_name='下一次复习日期')),
                ('repetition', models.IntegerField(default=0, verbose_name='复习次数')),
                ('last_quality', models.IntegerField(default=0, verbose_name='最后一次质量评分')),
                ('last_review_date', models.DateField(verbose_name='最后一次复习日期')),
                ('status', models.CharField(choices=[('learning', '未学习'), ('reviewing', '复习中'), ('mastered', '已掌握')], default='learning', max_length=10, verbose_name='状态')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizbank.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review_date'], name='users_learn_user_id_b8c390_idx'), models.Index(fields=['status'], name='users_learn_status_cfca50_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseLearningStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning', models.IntegerField(default=0, verbose_name='未学习的试题数量')),
                ('reviewing', models.IntegerField(default=0, verbose_name='复习中的试题数量')),
                ('mastered', models.IntegerField(default=0, verbose_name='已掌握的试题数量')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_statuses', to='quizbank.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_learning_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '课程学习状态',
                'verbose_name_plural': '课程学习状态',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
